name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test Rails
    uses: alphagov/govuk-infrastructure/.github/workflows/test-rails.yaml@debug-ci-workflow
    with:
      requiresJavaScript: true
      requiresRedis: true
      requiresMySQL: true
      mysqlUsername: whitehall
      mysqlPassword: whitehall
